name: Event Filters /7 Activity Types
on:
    workflow_dispatch:  
    pull_request:
        types: [opened,closed,reopened]
        branches:
            -main

jobs:
    echo:
        runs-on: ubuntu-latest
        steps:
            - name: Print message
              run: echo "PR opened in main branch"  